version: '3'

services:

    mysql-development:
        image: mysql:8.0.22
        volumes:
            - bankingapp-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: helloworld
            MYSQL_DATABASE: bankingapp

volumes:
    bankingapp-mysql-data:
